### ISSUE TITLE
Scraper is sometimes not catching lodgement dates

### ISSUE THREAD

**Issue by jamezpolley** [planningalerts-scrapers/yarra_ranges#2] opened 2019-05-06 07:57 UTC
As a result, we have a number of recent results with a scraped date but not a received date.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ndvh)

**Comment by mlandauer** [comment] 2019-05-07 02:39
This is one application that is missing the received date https://www.planningalerts.org.au/applications/1194376

**Comment by mlandauer** [comment] 2019-05-07 02:44
I'm going to close this as a "can't reproduce". The application on the council website shows the received date in the expected place. Other applications from the same council are bringing in the received date without problem.

However, because #3 has been fixed, this very old application will not get rescraped. So, it's stuck the way it is unfortunately.

**Closed by mlandauer** 2019-05-07 02:44 UTC
